### ISSUE TITLE
[Bug]: Crashes on load with a mixin issues with Create, Tough as Nails and Diet mods

### ISSUE THREAD

**Issue by AnimeniacYuuto** [TheIllusiveC4/Diet#124] opened 2022-04-07 05:17 UTC
### What happened?

I try to start the game with Create, Diet, TAN, and fly wheel installed and it crashes. The crash only occurs with all 3 mods installed. Also reporting to their authors

### How do you trigger this bug?

1. make a pack with Create, Diet, TAN, and fly wheel
2. start game
3. crash
...

### Forge Version

1.16.5 - 36.2.20

### Mod Version

Diet - 1.0.3.0

### Other Relevant Mod Versions

Create - 0.3.2g
Fly Wheel - 0.2.5
Tough as Nails - 4.1.0.9

### Relevant Log Outputs

https://pastebin.com/J357zWZM

**Comment by TheIllusiveC4** [comment] 2022-04-07 05:39
Duplicate of https://github.com/TheIllusiveC4/Diet/issues/123

**Closed as completed by TheIllusiveC4** 2022-04-07 05:39 UTC
Labels: type: bug, status: duplicate
